//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_GoDinghy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GoDinghyDBEntities : DbContext
    {
        public GoDinghyDBEntities()
            : base("name=GoDinghyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyTable> CompanyTables { get; set; }
        public virtual DbSet<CustomersTable> CustomersTables { get; set; }
        public virtual DbSet<UsersTable> UsersTables { get; set; }
        public virtual DbSet<UsersView> UsersViews { get; set; }
    
        public virtual int spAddUser(string vFirstName, string vLastName, string vInitials, Nullable<bool> vIsAdmin, Nullable<bool> vIsNormal, string vPassword, Nullable<bool> vActiv)
        {
            var vFirstNameParameter = vFirstName != null ?
                new ObjectParameter("vFirstName", vFirstName) :
                new ObjectParameter("vFirstName", typeof(string));
    
            var vLastNameParameter = vLastName != null ?
                new ObjectParameter("vLastName", vLastName) :
                new ObjectParameter("vLastName", typeof(string));
    
            var vInitialsParameter = vInitials != null ?
                new ObjectParameter("vInitials", vInitials) :
                new ObjectParameter("vInitials", typeof(string));
    
            var vIsAdminParameter = vIsAdmin.HasValue ?
                new ObjectParameter("vIsAdmin", vIsAdmin) :
                new ObjectParameter("vIsAdmin", typeof(bool));
    
            var vIsNormalParameter = vIsNormal.HasValue ?
                new ObjectParameter("vIsNormal", vIsNormal) :
                new ObjectParameter("vIsNormal", typeof(bool));
    
            var vPasswordParameter = vPassword != null ?
                new ObjectParameter("vPassword", vPassword) :
                new ObjectParameter("vPassword", typeof(string));
    
            var vActivParameter = vActiv.HasValue ?
                new ObjectParameter("vActiv", vActiv) :
                new ObjectParameter("vActiv", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddUser", vFirstNameParameter, vLastNameParameter, vInitialsParameter, vIsAdminParameter, vIsNormalParameter, vPasswordParameter, vActivParameter);
        }
    
        public virtual ObjectResult<spLogin_Result> spLogin(string vInitials, string vPassword)
        {
            var vInitialsParameter = vInitials != null ?
                new ObjectParameter("vInitials", vInitials) :
                new ObjectParameter("vInitials", typeof(string));
    
            var vPasswordParameter = vPassword != null ?
                new ObjectParameter("vPassword", vPassword) :
                new ObjectParameter("vPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLogin_Result>("spLogin", vInitialsParameter, vPasswordParameter);
        }
    }
}
