//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_GoDinghy
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTable
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsNormal { get; set; }
        public byte[] Password { get; set; }
        public Nullable<bool> Activ { get; set; }
        public Nullable<System.Guid> Salt { get; set; }
    }
}
